name: tf_py310
channels:
  - conda-forge
  - nvidia
dependencies:
  - python=3.10
  - pip
  - cudatoolkit=11.8.0
  - cuda-nvcc=11.3.58+

  - pip:
    - nvidia-cudnn-cu11==8.6.0.163
    - tensorflow==2.12.*
    - keras-tuner
    - matplotlib
    - scipy
    - prettytable
    - seaborn
